server:
  port: 9000
spring:
  application:
    name: 'Myga'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myga?serverTimezone=UTC
    username: TenCo
    password: 2002TenCo
  mvc:
#    static-path-pattern: static/**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
#      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 1500MB
#  devtools:
#    restart:
#      enabled: true
#      additional-path: src/main/java
#      exclude: static/**